### ISSUE TITLE
Config testes para o BackEnd e FrontEnd

### ISSUE THREAD

**Issue by NilvanPeres** [Coffee-and-Chat/Scantastic#7]
### Descrição:
Realizar a configuração inicial dos repositórios do back-end e front-end.

### Tarefas:
- [x] Configurar com as lib desejadas os testes para o back.
- [x] Configurar com as lib desejadas os testes para o front.
- [x] Criar um arquivo de teste para implementar o uso da lib.

### Critério de aceitação:
Print dos testes que foram criados.

**Comment by NilvanPeres** [comment]
Configuração iniciais dos arquivos foram feitas, e o arquivo aleátorio para testar a implementação da lib.
![Screenshot from 2021-06-10 11-58-12](https://user-images.githubusercontent.com/54211866/121549234-0e9f9d00-c9e4-11eb-8766-8f2e7a0497d7.png)

**Comment by francisco1code** [comment]
Perfeito Nilvan!

**Comment by francisco1code** [comment]
O ambiente de testes no back-end já foi implementado.
